In [1]:
import re

In [35]:
pattern1 = "abc"




In [36]:
#occurance of any character
print("Occurences of any character: ",re.match(r".+",pattern1))


Occurences of any character:  <_sre.SRE_Match object; span=(0, 3), match='abc'>


In [16]:
pattern1 = "9876 efg 98"
print("Occurences of A_Za-z: ",re.search(r"[a-z]+",pattern1))



Occurences of A_Za-z:  <_sre.SRE_Match object; span=(5, 8), match='efg'>


In [40]:
pattern1 = "ab"
print("Occurences of ab*: ",re.search(r"ab?",pattern1))



Occurences of ab*:  <_sre.SRE_Match object; span=(0, 2), match='ab'>


In [53]:
pattern1 = "12a"
if re.match(r"[a-z]+",pattern1) != None:
    print("Match!")
else:
    print("No Match!")

No Match!


In [54]:
pattern1 = "a12"
if re.match(r"[a-z]+",pattern1) != None:
    print("Match!")
else:
    print("No Match!")

Match!


In [55]:
pattern1 = "bac"
if re.match(r"ab?",pattern1) != None:
    print("Match!")
else:
    print("No Match!")

No Match!


In [58]:
pattern1 = "abcc"
if re.match(r"ab?",pattern1) != None:
    print("Match!")
else:
    print("No Match!")

Match!


In [63]:
# Introduction to Python Regular Expressions

# Importing Libraries
import re

pattern1 = "Apples are tasty"
pattern2 = "Today I feel like crying."

if re.match(r"^Apples",pattern1):
    print("Matches!")
else:
    print("No Match!")
    


Matches!


In [60]:
if re.search(r"\.$",pattern2):
    print("Match!")
else:
    print("No Match!")

Match!


In [7]:

import re

pattern1 = "I love Avengers" #I love Justice League

print(re.sub(r"Avengers","Justice League",pattern1))

print(re.sub(r"[a-z]","0",pattern1,2,flags=re.I))
print(re.sub(r"[a-z]","0",pattern1,1,flags=re.I))
print(re.sub(r"[a-z]","0",pattern1,3,flags=re.I))
print(re.sub(r"[a-z]","0",pattern1,))

I love Justice League
0 0ove Avengers
0 love Avengers
0 00ve Avengers
I 0000 A0000000


In [8]:
sentence1 = "Welcome to the year 2018"
sentence2 = "Just ~%* ++++--- arrived at @Jack's place. #fun"
sentence3 = "I                  love                u"



In [11]:
#substitute digits with space
sentence1_modified = re.sub(r'\d','',sentence1)
print(sentence1_modified)

Welcome to the year 


In [16]:
sentence2_modified = re.sub(r'[@#+%\*-.\']','',sentence2)
print(sentence2_modified)


Just ~  arrived at Jacks place fun


In [39]:
#to remove all special characters
sentence2 = "Just ~%* ++++--- arrived at @Jack's place. #fun"
sentence2_modified = re.sub(r'\W',' ',sentence2)
print(sentence2_modified)


Just             arrived at  Jack s place   fun


In [38]:
#to remove normal characters
sentence2 = "Just ~%* ++++--- arrived at @Jack's place. #fun"
sentence2_modified = re.sub(r'\w',' ',sentence2)
print(sentence2_modified)

     ~%* ++++---            @    '       . #   


In [40]:
#to replace one or more spaces
sentence2 = "Just ~%*                     ++++--- arrived at @Jack's place. #fun"
sentence2_modified = re.sub(r'\s+',' ',sentence2)                               
print(sentence2_modified)



Just ~%* ++++--- arrived at @Jack's place. #fun


In [43]:
#remove more than one white spaces before and after letters
sentence2_modified = re.sub(r"\s+[a-zA-Z]\s+",' ',sentence2_modified)
print(sentence2_modified)

Just ~%* ++++--- arrived at @Jack's place. #fun


In [45]:
sentence3 = "I                  love                u"
sentence3_modified = re.sub(r'\s+',' ',sentence3) 
print(sentence3_modified)

I love u


In [57]:
X = ["This is a wolf @scary",
     "Welcome to the jungle #missing",
     "111322 the number to know",
     "Remember the name s - John",
     "I                love               you"]


for i in range(len(X)):
    #print all except special characters
    X[i] = re.sub(r"\W"," ",X[i])
    print(X[i] ) 
    X[i] = re.sub(r"\d"," ",X[i])
    print(X[i])
    X[i] = re.sub(r"\s+[a-z]\s+"," ",X[i],flags=re.I)
    print(X[i])
    #subsitite more than one space
    X[i] = re.sub(r"\s+"," ",X[i])
    print(X[i])
    X[i] = re.sub(r"^\s","",X[i])
    print(X[i])
    X[i] = re.sub(r"\s$","",X[i])
    print(X[i])

This is a wolf  scary
This is a wolf  scary
This is wolf  scary
This is wolf scary
This is wolf scary
This is wolf scary
Welcome to the jungle  missing
Welcome to the jungle  missing
Welcome to the jungle  missing
Welcome to the jungle missing
Welcome to the jungle missing
Welcome to the jungle missing
111322 the number to know
       the number to know
       the number to know
 the number to know
the number to know
the number to know
Remember the name s   John
Remember the name s   John
Remember the name John
Remember the name John
Remember the name John
Remember the name John
I                love               you
I                love               you
I                love               you
I love you
I love you
I love you


In [59]:
#substitte beginning spaces
X =  "  I                love               you  "
X = re.sub(r"^\s","",X)
print(X)

 I                love               you  


In [60]:
#substitte trailing spaces
X =  "  I                love               you  "
X = re.sub(r"\s$","",X)
print(X)

  I                love               you 


In [61]:
import numpy as np

# arange()
# np.arange([start,] stop[, step,], dtype=None)
np.arange(10)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(1,10)



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [64]:
np.arange(1,10,0.5)



array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [65]:
np.arange(1,10,dtype='float64')


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
# Examining the ndarray
arr = np.arange(1,10)
print(arr)



[1 2 3 4 5 6 7 8 9]


In [69]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)



1
(9,)
9
int32
4


In [71]:
# Memory Usage
print(arr.itemsize * arr.size)

# Why use Numpy? Compare the time to do the same operation using
# numpy and normal python lists
# %timeit list1 = range(1,1000)
# %timeit list2 = np.arange(1,1000)


# Important functions in numpy
# List to array
print(np.asarray([1,2,3,4,5]))



36
[1 2 3 4 5]


In [73]:
list2d = [[1,2,3],[4,5,6]]
arr2d = np.asarray(list2d)
print(arr2d)
# Generate zeros
# zeros(shape, dtype=float, order='C')

listzeros = np.zeros((3,4), dtype='int32')
print(listzeros)
# Linspace
# np.linspace(start, stop, num=50, endpoint=True, retstep=False)



[[1 2 3]
 [4 5 6]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [74]:
print(np.linspace(1,4,num=4))
print(np.linspace(1,4,num=8))
print(np.linspace(1,4,num=8,endpoint=False))



[1. 2. 3. 4.]
[1.         1.42857143 1.85714286 2.28571429 2.71428571 3.14285714
 3.57142857 4.        ]
[1.    1.375 1.75  2.125 2.5   2.875 3.25  3.625]


In [76]:
# Max, min, mean, median, std etc
# np.max(a, axis=None, out=None, keepdims=False)
# np.min(a, axis=None, out=None, keepdims=False)
# np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
# np.median(a, axis=None, out=None, overwrite_input=False)
# np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)
# np.sum(a, axis=None, dtype=None, out=None, keepdims=False)

rarr = np.random.random((3,4))
print(rarr)
print(np.max(rarr, axis=0))

print(np.max(rarr, axis=1))



[[0.08234097 0.03669845 0.26382538 0.193715  ]
 [0.19088079 0.17563507 0.10132734 0.75091069]
 [0.4024851  0.85343397 0.21136796 0.74030123]]
[0.4024851  0.85343397 0.26382538 0.75091069]
[0.26382538 0.75091069 0.85343397]


In [79]:
# Reshaping
# np.reshape(a, newshape, order='C')
new_rarr = np.reshape(rarr, (12,))
print(new_rarr)
new_rarr = np.reshape(rarr, (12,1))
print(new_rarr)



[0.08234097 0.03669845 0.26382538 0.193715   0.19088079 0.17563507
 0.10132734 0.75091069 0.4024851  0.85343397 0.21136796 0.74030123]
[[0.08234097]
 [0.03669845]
 [0.26382538]
 [0.193715  ]
 [0.19088079]
 [0.17563507]
 [0.10132734]
 [0.75091069]
 [0.4024851 ]
 [0.85343397]
 [0.21136796]
 [0.74030123]]


In [80]:
# Slicing
rarr = np.random.random((4,5))

rarr[:,:]
rarr[1:3,:]

rarr[:,1:]
rarr[:,1:3]

rarr[1:3,1:3]

rarr[[0,3],:]
rarr[:,[0,3]]


rarr[:-1,:]
rarr[-1:,:]

array([[0.46602255, 0.53619318, 0.25796926, 0.46279149, 0.77022756]])

In [ ]:
# Natural Language Processing using NLTK

# Install NLTK - pip install nltk

# Tokenization of paragraphs/sentences
import nltk


paragraph = "Thank you all so very much. Thank you to the Academy. 
               Thank you to all of you in this room. I have to congratulate 
               the other incredible nominees this year. The Revenant was 
               the product of the tireless efforts of an unbelievable cast
               and crew. First off, to my brother in this endeavor, Mr. Tom 
               Hardy. Tom, your talent on screen can only be surpassed by 
               your friendship off screen … thank you for creating a t
               ranscendent cinematic experience. Thank you to everybody at 
               Fox and New Regency … my entire team. I have to thank 
               everyone from the very onset of my career … To my parents; 
               none of this would be possible without you. And to my 
               friends, I love you dearly; you know who you are. And lastly,
               I just want to say this: Making The Revenant was about
               man's relationship to the natural world. A world that we
               collectively felt in 2015 as the hottest year in recorded
               history. Our production needed to move to the southern
               tip of this planet just to be able to find snow. Climate
               change is real, it is happening right now. It is the most
               urgent threat facing our entire species, and we need to work
               collectively together and stop procrastinating. We need to
               support leaders around the world who do not speak for the 
               big polluters, but who speak for all of humanity, for the
               indigenous people of the world, for the billions and 
               billions of underprivileged people out there who would be
               most affected by this. For our children’s children, and 
               for those people out there whose voices have been drowned
               out by the politics of greed. I thank you all for this 
               amazing award tonight. Let us not take this planet for 
               granted. I do not take tonight for granted. Thank you so very much."
               


In [84]:
# Tokenizing sentences
sentences = nltk.sent_tokenize(paragraph)
print(sentences)


['Thank you all so very much.', 'Thank you to the Academy.', 'Thank you to all of you in this room.', 'I have to congratulate \n               the other incredible nominees this year.', 'The Revenant was \n               the product of the tireless efforts of an unbelievable cast\n               and crew.', 'First off, to my brother in this endeavor, Mr. Tom \n               Hardy.', 'Tom, your talent on screen can only be surpassed by \n               your friendship off screen … thank you for creating a t\n               ranscendent cinematic experience.', 'Thank you to everybody at \n               Fox and New Regency … my entire team.', 'I have to thank \n               everyone from the very onset of my career … To my parents; \n               none of this would be possible without you.', 'And to my \n               friends, I love you dearly; you know who you are.', "And lastly,\n               I just want to say this: Making The Revenant was about\n               man's relations

In [85]:

# Tokenizing words
words = nltk.word_tokenize(paragraph)
print(words)

['Thank', 'you', 'all', 'so', 'very', 'much', '.', 'Thank', 'you', 'to', 'the', 'Academy', '.', 'Thank', 'you', 'to', 'all', 'of', 'you', 'in', 'this', 'room', '.', 'I', 'have', 'to', 'congratulate', 'the', 'other', 'incredible', 'nominees', 'this', 'year', '.', 'The', 'Revenant', 'was', 'the', 'product', 'of', 'the', 'tireless', 'efforts', 'of', 'an', 'unbelievable', 'cast', 'and', 'crew', '.', 'First', 'off', ',', 'to', 'my', 'brother', 'in', 'this', 'endeavor', ',', 'Mr.', 'Tom', 'Hardy', '.', 'Tom', ',', 'your', 'talent', 'on', 'screen', 'can', 'only', 'be', 'surpassed', 'by', 'your', 'friendship', 'off', 'screen', '…', 'thank', 'you', 'for', 'creating', 'a', 't', 'ranscendent', 'cinematic', 'experience', '.', 'Thank', 'you', 'to', 'everybody', 'at', 'Fox', 'and', 'New', 'Regency', '…', 'my', 'entire', 'team', '.', 'I', 'have', 'to', 'thank', 'everyone', 'from', 'the', 'very', 'onset', 'of', 'my', 'career', '…', 'To', 'my', 'parents', ';', 'none', 'of', 'this', 'would', 'be', 'poss

In [89]:
import nltk
from nltk.stem import PorterStemmer

paragraph = "Thank you all so very much. Thank you to the Academy. 
               Thank you to all of you in this room. I have to congratulate 
               the other incredible nominees this year. The Revenant was 
               the product of the tireless efforts of an unbelievable cast
               and crew. First off, to my brother in this endeavor, Mr. Tom 
               Hardy. Tom, your talent on screen can only be surpassed by 
               your friendship off screen … thank you for creating a t
               ranscendent cinematic experience. Thank you to everybody at 
               Fox and New Regency … my entire team. I have to thank 
               everyone from the very onset of my career … To my parents; 
               none of this would be possible without you. And to my 
               friends, I love you dearly; you know who you are. And lastly,
               I just want to say this: Making The Revenant was about
               man's relationship to the natural world. A world that we
               collectively felt in 2015 as the hottest year in recorded
               history. Our production needed to move to the southern
               tip of this planet just to be able to find snow. Climate
               change is real, it is happening right now. It is the most
               urgent threat facing our entire species, and we need to work
               collectively together and stop procrastinating. We need to
               support leaders around the world who do not speak for the 
               big polluters, but who speak for all of humanity, for the
               indigenous people of the world, for the billions and 
               billions of underprivileged people out there who would be
               most affected by this. For our children’s children, and 
               for those people out there whose voices have been drowned
               out by the politics of greed. I thank you all for this 
               amazing award tonight. Let us not take this planet for 
               granted. I do not take tonight for granted. Thank you so very much."
               
       

SyntaxError: EOL while scanning string literal (<ipython-input-89-681847fcc2f7>, line 4)

In [90]:
print(paragraph)

Thank you all so very much. Thank you to the Academy. 
               Thank you to all of you in this room. I have to congratulate 
               the other incredible nominees this year. The Revenant was 
               the product of the tireless efforts of an unbelievable cast
               and crew. First off, to my brother in this endeavor, Mr. Tom 
               Hardy. Tom, your talent on screen can only be surpassed by 
               your friendship off screen … thank you for creating a t
               ranscendent cinematic experience. Thank you to everybody at 
               Fox and New Regency … my entire team. I have to thank 
               everyone from the very onset of my career … To my parents; 
               none of this would be possible without you. And to my 
               friends, I love you dearly; you know who you are. And lastly,
               I just want to say this: Making The Revenant was about
               man's relationship to the natural world. A 

In [93]:
sentences = nltk.sent_tokenize(paragraph)
print(sentences)

['Thank you all so very much.', 'Thank you to the Academy.', 'Thank you to all of you in this room.', 'I have to congratulate \n               the other incredible nominees this year.', 'The Revenant was \n               the product of the tireless efforts of an unbelievable cast\n               and crew.', 'First off, to my brother in this endeavor, Mr. Tom \n               Hardy.', 'Tom, your talent on screen can only be surpassed by \n               your friendship off screen … thank you for creating a t\n               ranscendent cinematic experience.', 'Thank you to everybody at \n               Fox and New Regency … my entire team.', 'I have to thank \n               everyone from the very onset of my career … To my parents; \n               none of this would be possible without you.', 'And to my \n               friends, I love you dearly; you know who you are.', "And lastly,\n               I just want to say this: Making The Revenant was about\n               man's relations

In [95]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
# Stemming
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words]
    sentences[i] = ' '.join(words)      
    

In [96]:
print(sentences)

['thank you all so veri much .', 'thank you to the academi .', 'thank you to all of you in thi room .', 'I have to congratul the other incred nomine thi year .', 'the reven wa the product of the tireless effort of an unbeliev cast and crew .', 'first off , to my brother in thi endeavor , mr. tom hardi .', 'tom , your talent on screen can onli be surpass by your friendship off screen … thank you for creat a t ranscend cinemat experi .', 'thank you to everybodi at fox and new regenc … my entir team .', 'I have to thank everyon from the veri onset of my career … To my parent ; none of thi would be possibl without you .', 'and to my friend , I love you dearli ; you know who you are .', "and lastli , I just want to say thi : make the reven wa about man 's relationship to the natur world .", 'A world that we collect felt in 2015 as the hottest year in record histori .', 'our product need to move to the southern tip of thi planet just to be abl to find snow .', 'climat chang is real , it is h

In [98]:
#get all the words in its original form
word ='drinking'
stemmer.stem(word)

'drink'

In [103]:
#wordnet stemmer to get the sentences correct
import nltk
from nltk.stem import WordNetLemmatizer


               
               
sentences = nltk.sent_tokenize(paragraph)
lemmatizer = WordNetLemmatizer()

# Lemmatization
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words]
    sentences[i] = ' '.join(words)             

In [104]:
print(sentences)

['Thank you all so very much .', 'Thank you to the Academy .', 'Thank you to all of you in this room .', 'I have to congratulate the other incredible nominee this year .', 'The Revenant wa the product of the tireless effort of an unbelievable cast and crew .', 'First off , to my brother in this endeavor , Mr. Tom Hardy .', 'Tom , your talent on screen can only be surpassed by your friendship off screen … thank you for creating a t ranscendent cinematic experience .', 'Thank you to everybody at Fox and New Regency … my entire team .', 'I have to thank everyone from the very onset of my career … To my parent ; none of this would be possible without you .', 'And to my friend , I love you dearly ; you know who you are .', "And lastly , I just want to say this : Making The Revenant wa about man 's relationship to the natural world .", 'A world that we collectively felt in 2015 a the hottest year in recorded history .', 'Our production needed to move to the southern tip of this planet just t

In [108]:
#stop words
#remove stop words
from nltk.corpus import stopwords
sentences = nltk.sent_tokenize(paragraph)


# Removing stopwords
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [word for word in words if word not in stopwords.words('english')]
    sentences[i] = ' '.join(words)        
print(sentences)

['Thank much .', 'Thank Academy .', 'Thank room .', 'I congratulate incredible nominees year .', 'The Revenant product tireless efforts unbelievable cast crew .', 'First , brother endeavor , Mr. Tom Hardy .', 'Tom , talent screen surpassed friendship screen … thank creating ranscendent cinematic experience .', 'Thank everybody Fox New Regency … entire team .', 'I thank everyone onset career … To parents ; none would possible without .', 'And friends , I love dearly ; know .', "And lastly , I want say : Making The Revenant man 's relationship natural world .", 'A world collectively felt 2015 hottest year recorded history .', 'Our production needed move southern tip planet able find snow .', 'Climate change real , happening right .', 'It urgent threat facing entire species , need work collectively together stop procrastinating .', 'We need support leaders around world speak big polluters , speak humanity , indigenous people world , billions billions underprivileged people would affected 

In [112]:
#pos tagging
# POS Tagging
words = nltk.word_tokenize(paragraph)

tagged_words = nltk.pos_tag(words)

# Tagged word paragraph
word_tags = []
for tw in tagged_words:
    word_tags.append(tw[0]+"_"+tw[1])

tagged_paragraph = ' '.join(word_tags)
print(words)


['Thank', 'you', 'all', 'so', 'very', 'much', '.', 'Thank', 'you', 'to', 'the', 'Academy', '.', 'Thank', 'you', 'to', 'all', 'of', 'you', 'in', 'this', 'room', '.', 'I', 'have', 'to', 'congratulate', 'the', 'other', 'incredible', 'nominees', 'this', 'year', '.', 'The', 'Revenant', 'was', 'the', 'product', 'of', 'the', 'tireless', 'efforts', 'of', 'an', 'unbelievable', 'cast', 'and', 'crew', '.', 'First', 'off', ',', 'to', 'my', 'brother', 'in', 'this', 'endeavor', ',', 'Mr.', 'Tom', 'Hardy', '.', 'Tom', ',', 'your', 'talent', 'on', 'screen', 'can', 'only', 'be', 'surpassed', 'by', 'your', 'friendship', 'off', 'screen', '…', 'thank', 'you', 'for', 'creating', 'a', 't', 'ranscendent', 'cinematic', 'experience', '.', 'Thank', 'you', 'to', 'everybody', 'at', 'Fox', 'and', 'New', 'Regency', '…', 'my', 'entire', 'team', '.', 'I', 'have', 'to', 'thank', 'everyone', 'from', 'the', 'very', 'onset', 'of', 'my', 'career', '…', 'To', 'my', 'parents', ';', 'none', 'of', 'this', 'would', 'be', 'poss

In [113]:

print(tagged_words)


[('Thank', 'NNP'), ('you', 'PRP'), ('all', 'DT'), ('so', 'RB'), ('very', 'RB'), ('much', 'JJ'), ('.', '.'), ('Thank', 'VB'), ('you', 'PRP'), ('to', 'TO'), ('the', 'DT'), ('Academy', 'NNP'), ('.', '.'), ('Thank', 'NNP'), ('you', 'PRP'), ('to', 'TO'), ('all', 'DT'), ('of', 'IN'), ('you', 'PRP'), ('in', 'IN'), ('this', 'DT'), ('room', 'NN'), ('.', '.'), ('I', 'PRP'), ('have', 'VBP'), ('to', 'TO'), ('congratulate', 'VB'), ('the', 'DT'), ('other', 'JJ'), ('incredible', 'JJ'), ('nominees', 'NNS'), ('this', 'DT'), ('year', 'NN'), ('.', '.'), ('The', 'DT'), ('Revenant', 'NNP'), ('was', 'VBD'), ('the', 'DT'), ('product', 'NN'), ('of', 'IN'), ('the', 'DT'), ('tireless', 'NN'), ('efforts', 'NNS'), ('of', 'IN'), ('an', 'DT'), ('unbelievable', 'JJ'), ('cast', 'NN'), ('and', 'CC'), ('crew', 'NN'), ('.', '.'), ('First', 'NNP'), ('off', 'RB'), (',', ','), ('to', 'TO'), ('my', 'PRP$'), ('brother', 'NN'), ('in', 'IN'), ('this', 'DT'), ('endeavor', 'NN'), (',', ','), ('Mr.', 'NNP'), ('Tom', 'NNP'), ('Har

In [114]:

print(word_tags)

['Thank_NNP', 'you_PRP', 'all_DT', 'so_RB', 'very_RB', 'much_JJ', '._.', 'Thank_VB', 'you_PRP', 'to_TO', 'the_DT', 'Academy_NNP', '._.', 'Thank_NNP', 'you_PRP', 'to_TO', 'all_DT', 'of_IN', 'you_PRP', 'in_IN', 'this_DT', 'room_NN', '._.', 'I_PRP', 'have_VBP', 'to_TO', 'congratulate_VB', 'the_DT', 'other_JJ', 'incredible_JJ', 'nominees_NNS', 'this_DT', 'year_NN', '._.', 'The_DT', 'Revenant_NNP', 'was_VBD', 'the_DT', 'product_NN', 'of_IN', 'the_DT', 'tireless_NN', 'efforts_NNS', 'of_IN', 'an_DT', 'unbelievable_JJ', 'cast_NN', 'and_CC', 'crew_NN', '._.', 'First_NNP', 'off_RB', ',_,', 'to_TO', 'my_PRP$', 'brother_NN', 'in_IN', 'this_DT', 'endeavor_NN', ',_,', 'Mr._NNP', 'Tom_NNP', 'Hardy_NNP', '._.', 'Tom_NNP', ',_,', 'your_PRP$', 'talent_NN', 'on_IN', 'screen_NN', 'can_MD', 'only_RB', 'be_VB', 'surpassed_VBN', 'by_IN', 'your_PRP$', 'friendship_NN', 'off_IN', 'screen_JJ', '…_NNP', 'thank_NN', 'you_PRP', 'for_IN', 'creating_VBG', 'a_DT', 't_JJ', 'ranscendent_NN', 'cinematic_JJ', 'experience_

In [115]:
paragraph = """The Taj Mahal was built by Emperor Shah Jahan"""
               
               
# POS Tagging
words = nltk.word_tokenize(paragraph)

tagged_words = nltk.pos_tag(words)


In [116]:

# Named entity recognition
namedEnt = nltk.ne_chunk(tagged_words)
namedEnt.draw()

"""
ORGANIZATION	Georgia-Pacific Corp., WHO
PERSON	Eddy Bonte, President Obama
LOCATION	Murray River, Mount Everest
DATE	June, 2008-06-29
TIME	two fifty a m, 1:30 p.m.
MONEY	175 million Canadian Dollars, GBP 10.40
PERCENT	twenty pct, 18.75 %
FACILITY	Washington Monument, Stonehenge
GPE	South East Asia, Midlothian
"""

'\nORGANIZATION\tGeorgia-Pacific Corp., WHO\nPERSON\tEddy Bonte, President Obama\nLOCATION\tMurray River, Mount Everest\nDATE\tJune, 2008-06-29\nTIME\ttwo fifty a m, 1:30 p.m.\nMONEY\t175 million Canadian Dollars, GBP 10.40\nPERCENT\ttwenty pct, 18.75 %\nFACILITY\tWashington Monument, Stonehenge\nGPE\tSouth East Asia, Midlothian\n'

In [119]:
import nltk
import re

paragraph = "Thank you all so very much. Thank you to the Academy. 
               Thank you to all of you in this room. I have to congratulate 
               the other incredible nominees this year. The Revenant was 
               the product of the tireless efforts of an unbelievable cast
               and crew. First off, to my brother in this endeavor, Mr. Tom 
               Hardy. Tom, your talent on screen can only be surpassed by 
               your friendship off screen … thank you for creating a t
               ranscendent cinematic experience. Thank you to everybody at 
               Fox and New Regency … my entire team. I have to thank 
               everyone from the very onset of my career … To my parents; 
               none of this would be possible without you. And to my 
               friends, I love you dearly; you know who you are. And lastly,
               I just want to say this: Making The Revenant was about
               man's relationship to the natural world. A world that we
               collectively felt in 2015 as the hottest year in recorded
               history. Our production needed to move to the southern
               tip of this planet just to be able to find snow. Climate
               change is real, it is happening right now. It is the most
               urgent threat facing our entire species, and we need to work
               collectively together and stop procrastinating. We need to
               support leaders around the world who do not speak for the 
               big polluters, but who speak for all of humanity, for the
               indigenous people of the world, for the billions and 
               billions of underprivileged people out there who would be
               most affected by this. For our children’s children, and 
               for those people out there whose voices have been drowned
               out by the politics of greed. I thank you all for this 
               amazing award tonight. Let us not take this planet for 
               granted. I do not take tonight for granted. Thank you so very much."
                

               


SyntaxError: EOL while scanning string literal (<ipython-input-119-8b0db98b8356>, line 4)

In [120]:
print(paragraph)

Thank you all so very much. Thank you to the Academy. 
               Thank you to all of you in this room. I have to congratulate 
               the other incredible nominees this year. The Revenant was 
               the product of the tireless efforts of an unbelievable cast
               and crew. First off, to my brother in this endeavor, Mr. Tom 
               Hardy. Tom, your talent on screen can only be surpassed by 
               your friendship off screen … thank you for creating a t
               ranscendent cinematic experience. Thank you to everybody at 
               Fox and New Regency … my entire team. I have to thank 
               everyone from the very onset of my career … To my parents; 
               none of this would be possible without you. And to my 
               friends, I love you dearly; you know who you are. And lastly,
               I just want to say this: Making The Revenant was about
               man's relationship to the natural world. A 

In [122]:
# Tokenize sentences
#make all the sentences lower, remove speacial characters, remove extra spaces
dataset = nltk.sent_tokenize(paragraph)
for i in range(len(dataset)):
    dataset[i] = dataset[i].lower()
    dataset[i] = re.sub(r'\W',' ',dataset[i])
    dataset[i] = re.sub(r'\s+',' ',dataset[i])
print(dataset)

['thank you all so very much ', 'thank you to the academy ', 'thank you to all of you in this room ', 'i have to congratulate the other incredible nominees this year ', 'the revenant was the product of the tireless efforts of an unbelievable cast and crew ', 'first off to my brother in this endeavor mr tom hardy ', 'tom your talent on screen can only be surpassed by your friendship off screen thank you for creating a t ranscendent cinematic experience ', 'thank you to everybody at fox and new regency my entire team ', 'i have to thank everyone from the very onset of my career to my parents none of this would be possible without you ', 'and to my friends i love you dearly you know who you are ', 'and lastly i just want to say this making the revenant was about man s relationship to the natural world ', 'a world that we collectively felt in 2015 as the hottest year in recorded history ', 'our production needed to move to the southern tip of this planet just to be able to find snow ', 'cl

In [123]:
# Creating word histogram
word2count = {}
for data in dataset:
    words = nltk.word_tokenize(data)
    for word in words:
        if word not in word2count.keys():
            word2count[word] = 1
        else:
            word2count[word] += 1

In [124]:
print(words)

['thank', 'you', 'so', 'very', 'much']


In [125]:
print(word2count)

{'thank': 8, 'you': 12, 'all': 4, 'so': 2, 'very': 3, 'much': 2, 'to': 16, 'the': 17, 'academy': 1, 'of': 10, 'in': 4, 'this': 9, 'room': 1, 'i': 6, 'have': 3, 'congratulate': 1, 'other': 1, 'incredible': 1, 'nominees': 1, 'year': 2, 'revenant': 2, 'was': 2, 'product': 1, 'tireless': 1, 'efforts': 1, 'an': 1, 'unbelievable': 1, 'cast': 1, 'and': 8, 'crew': 1, 'first': 1, 'off': 2, 'my': 5, 'brother': 1, 'endeavor': 1, 'mr': 1, 'tom': 2, 'hardy': 1, 'your': 2, 'talent': 1, 'on': 1, 'screen': 2, 'can': 1, 'only': 1, 'be': 4, 'surpassed': 1, 'by': 3, 'friendship': 1, 'for': 10, 'creating': 1, 'a': 2, 't': 1, 'ranscendent': 1, 'cinematic': 1, 'experience': 1, 'everybody': 1, 'at': 1, 'fox': 1, 'new': 1, 'regency': 1, 'entire': 2, 'team': 1, 'everyone': 1, 'from': 1, 'onset': 1, 'career': 1, 'parents': 1, 'none': 1, 'would': 2, 'possible': 1, 'without': 1, 'friends': 1, 'love': 1, 'dearly': 1, 'know': 1, 'who': 4, 'are': 1, 'lastly': 1, 'just': 2, 'want': 1, 'say': 1, 'making': 1, 'about': 

In [126]:
import heapq

In [127]:
word2count = {}
for data in dataset:
    words = nltk.word_tokenize(data)
    for word in words:
        if word not in word2count.keys():
            word2count[word] = 1
        else:
            word2count[word] += 1
            
# Selecting best 100 features
freq_words = heapq.nlargest(100,word2count,key=word2count.get)

In [130]:
print(freq_words)
print( word2count.keys(),word2count.values())

['the', 'to', 'you', 'of', 'for', 'this', 'thank', 'and', 'i', 'my', 'all', 'in', 'be', 'who', 'world', 'very', 'have', 'by', 'we', 'our', 'is', 'not', 'people', 'out', 'so', 'much', 'year', 'revenant', 'was', 'off', 'tom', 'your', 'screen', 'a', 'entire', 'would', 'just', 's', 'collectively', 'planet', 'it', 'most', 'need', 'do', 'speak', 'billions', 'there', 'children', 'tonight', 'take', 'granted', 'academy', 'room', 'congratulate', 'other', 'incredible', 'nominees', 'product', 'tireless', 'efforts', 'an', 'unbelievable', 'cast', 'crew', 'first', 'brother', 'endeavor', 'mr', 'hardy', 'talent', 'on', 'can', 'only', 'surpassed', 'friendship', 'creating', 't', 'ranscendent', 'cinematic', 'experience', 'everybody', 'at', 'fox', 'new', 'regency', 'team', 'everyone', 'from', 'onset', 'career', 'parents', 'none', 'possible', 'without', 'friends', 'love', 'dearly', 'know', 'are', 'lastly']
dict_keys(['thank', 'you', 'all', 'so', 'very', 'much', 'to', 'the', 'academy', 'of', 'in', 'this', 'r

In [134]:
# Converting sentences to vectors
X = []
for data in dataset:
    vector = []
    for word in freq_words:
        if word in nltk.word_tokenize(data):
            vector.append(1)
        else:
            vector.append(0)
    X.append(vector)
        


In [135]:
print(X)

[[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [137]:
X = np.asarray(X)
print(X)

[[0 0 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


In [140]:
# IDF Dictionary
word_idfs = {}
for word in freq_words:
    doc_count = 0
    for data in dataset:
        if word in nltk.word_tokenize(data):
            doc_count += 1
    word_idfs[word] = np.log(len(dataset)/(1+doc_count))

In [141]:
print(word_idfs)

{'the': 0.6466271649250525, 'to': 0.5596157879354227, 'you': 0.7419373447293773, 'of': 1.0986122886681098, 'for': 1.0986122886681098, 'this': 0.7419373447293773, 'thank': 0.8472978603872037, 'and': 0.965080896043587, 'i': 1.0986122886681098, 'my': 1.4350845252893227, 'all': 1.4350845252893227, 'in': 1.6582280766035324, 'be': 1.4350845252893227, 'who': 1.9459101490553132, 'world': 1.6582280766035324, 'very': 1.6582280766035324, 'have': 1.6582280766035324, 'by': 1.6582280766035324, 'we': 1.6582280766035324, 'our': 1.6582280766035324, 'is': 1.9459101490553132, 'not': 1.6582280766035324, 'people': 1.9459101490553132, 'out': 1.9459101490553132, 'so': 1.9459101490553132, 'much': 1.9459101490553132, 'year': 1.9459101490553132, 'revenant': 1.9459101490553132, 'was': 1.9459101490553132, 'off': 1.9459101490553132, 'tom': 1.9459101490553132, 'your': 2.3513752571634776, 'screen': 2.3513752571634776, 'a': 1.9459101490553132, 'entire': 1.9459101490553132, 'would': 1.9459101490553132, 'just': 1.94591

In [142]:
# TF Matrix
tf_matrix = {}
for word in freq_words:
    doc_tf = []
    for data in dataset:
        frequency = 0
        for w in nltk.word_tokenize(data):
            if word == w:
                frequency += 1
        tf_word = frequency/len(nltk.word_tokenize(data))
        doc_tf.append(tf_word)
    tf_matrix[word] = doc_tf

In [143]:
print(tf_matrix)

{'the': [0.0, 0.2, 0.0, 0.1, 0.2, 0.0, 0.0, 0.0, 0.043478260869565216, 0.0, 0.1, 0.06666666666666667, 0.05263157894736842, 0.0, 0.05, 0.10638297872340426, 0.045454545454545456, 0.0, 0.0, 0.0, 0.0], 'to': [0.0, 0.2, 0.1111111111111111, 0.1, 0.0, 0.09090909090909091, 0.0, 0.08333333333333333, 0.08695652173913043, 0.07692307692307693, 0.1, 0.0, 0.21052631578947367, 0.0, 0.05, 0.02127659574468085, 0.0, 0.0, 0.0, 0.0, 0.0], 'you': [0.16666666666666666, 0.2, 0.2222222222222222, 0.0, 0.0, 0.0, 0.043478260869565216, 0.08333333333333333, 0.043478260869565216, 0.23076923076923078, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1111111111111111, 0.0, 0.0, 0.2], 'of': [0.0, 0.0, 0.1111111111111111, 0.0, 0.13333333333333333, 0.0, 0.0, 0.0, 0.08695652173913043, 0.0, 0.0, 0.0, 0.05263157894736842, 0.0, 0.0, 0.06382978723404255, 0.045454545454545456, 0.0, 0.0, 0.0, 0.0], 'for': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.043478260869565216, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0851063829787234, 0.09090909090909091, 0

In [144]:
# Creating the Tf-Idf Model
tfidf_matrix = []
for word in tf_matrix.keys():
    tfidf = []
    for value in tf_matrix[word]:
        score = value * word_idfs[word]
        tfidf.append(score)
    tfidf_matrix.append(tfidf)   

In [145]:
print(tfidf_matrix)

[[0.0, 0.1293254329850105, 0.0, 0.06466271649250525, 0.1293254329850105, 0.0, 0.0, 0.0, 0.028114224561958803, 0.0, 0.06466271649250525, 0.04310847766167016, 0.034033008680265917, 0.0, 0.03233135824625263, 0.06879012392819707, 0.029392143860229657, 0.0, 0.0, 0.0, 0.0], [0.0, 0.11192315758708454, 0.062179531992824735, 0.05596157879354227, 0.0, 0.05087416253958388, 0.0, 0.046634648994618555, 0.04866224242916719, 0.04304736830272482, 0.05596157879354227, 0.0, 0.11781385009166792, 0.0, 0.027980789396771136, 0.011906718892243035, 0.0, 0.0, 0.0, 0.0, 0.0], [0.12365622412156288, 0.14838746894587548, 0.16487496549541716, 0.0, 0.0, 0.0, 0.0322581454230164, 0.06182811206078144, 0.0322581454230164, 0.171216310322164, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.08243748274770858, 0.0, 0.0, 0.14838746894587548], [0.0, 0.0, 0.12206803207423442, 0.0, 0.1464816384890813, 0.0, 0.0, 0.0, 0.09553150336244433, 0.0, 0.0, 0.0, 0.057821699403584725, 0.0, 0.0, 0.07012418863838998, 0.04993692221218681, 0.0, 0.0, 0.0, 