In [2]:
import torch


In [5]:
# 1 D tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [6]:
#2d tensor
b = torch.tensor([[2,2,1],[2,2,1],[2,2,1],[2,2,1]])
print(b)

tensor([[2, 2, 1],
        [2, 2, 1],
        [2, 2, 1],
        [2, 2, 1]])


In [7]:
print(a.shape)
print(a.shape)
print(b.size())
print(b.size())

torch.Size([3])
torch.Size([3])
torch.Size([4, 3])
torch.Size([4, 3])


In [8]:
#get the height and no of rows of a tensor
b.shape[0]

4

In [9]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c = torch.tensor([2,2,1], dtype = torch.float)

In [10]:
print(c)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])


In [11]:
c = torch.tensor([2,2,1], dtype = torch.float)

In [12]:
print(c)

tensor([2., 2., 1.])


In [13]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [14]:
print(c)
print(c.dtype)

tensor([2., 2., 1.])
torch.float32


In [15]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [16]:
print(c.mean())

tensor(1.6667)


In [17]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [18]:
print(c.std())

tensor(0.5774)


In [19]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [20]:

#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))


tensor([[2],
        [2],
        [1],
        [2],
        [2],
        [1],
        [2],
        [2],
        [1],
        [2],
        [2],
        [1]])


In [21]:
print(b.view(12))


tensor([2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1])


In [22]:
print(b.view(-1,4))


tensor([[2, 2, 1, 2],
        [2, 1, 2, 2],
        [1, 2, 2, 1]])


In [23]:
print(b.view(3,4))


tensor([[2, 2, 1, 2],
        [2, 1, 2, 2],
        [1, 2, 2, 1]])


In [24]:
#Assign b a new shape
b = b.view(1,-1)
print(b)


tensor([[2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1]])


In [25]:
print(b.shape)


torch.Size([1, 12])


In [27]:
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)




tensor([[[ 1.8555, -1.8024,  0.6892,  0.1512],
         [ 1.1822, -0.8297,  0.1402, -0.0331],
         [ 0.7504,  1.0702,  2.0091,  0.0718]],

        [[-0.2742, -0.4061, -0.8407,  0.1979],
         [-1.5558, -0.7182,  1.4773, -0.6227],
         [ 0.5690, -0.5575,  0.7154,  2.7133]]])


In [28]:
print(three_dim.view(2, 12))  # Reshape to 2 rows, 12 columns


tensor([[ 1.8555, -1.8024,  0.6892,  0.1512,  1.1822, -0.8297,  0.1402, -0.0331,
          0.7504,  1.0702,  2.0091,  0.0718],
        [-0.2742, -0.4061, -0.8407,  0.1979, -1.5558, -0.7182,  1.4773, -0.6227,
          0.5690, -0.5575,  0.7154,  2.7133]])


In [29]:
print(three_dim.view(2, -1))

tensor([[ 1.8555, -1.8024,  0.6892,  0.1512,  1.1822, -0.8297,  0.1402, -0.0331,
          0.7504,  1.0702,  2.0091,  0.0718],
        [-0.2742, -0.4061, -0.8407,  0.1979, -1.5558, -0.7182,  1.4773, -0.6227,
          0.5690, -0.5575,  0.7154,  2.7133]])


In [30]:

#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.8326, 0.6130, 0.6620, 0.6599],
        [0.5432, 0.8823, 0.6667, 0.7055],
        [0.9312, 0.0609, 0.6856, 0.8007],
        [0.0153, 0.8298, 0.3225, 0.4833]])


In [31]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1 
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-1.1508,  0.5559, -0.5223, -0.6465],
        [ 0.4921, -1.9520, -1.3231, -0.5330],
        [ 1.6174, -1.2058, -0.1029,  0.2684],
        [-0.0435,  1.3146,  3.0173,  0.3901]])
torch.float32


In [32]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([8, 8, 8, 6, 9])
torch.int64


In [33]:

#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[7, 9, 9],
        [8, 8, 7],
        [9, 6, 7]])


In [34]:
#Get the number of elemetns in in_array
print(torch.numel(in_array))
#Get the number of elemetns in in_array
print(torch.numel(in_array2))

5
9


In [35]:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [36]:

r2_like = torch.randn_like(r2, dtype=torch.double)    # Convert the data type of the tensor
print(r2_like)

tensor([[ 0.7363, -2.1354, -1.9716, -1.3013],
        [ 0.1763, -1.1475,  0.2758, -0.5159],
        [ 1.2068,  1.1527, -0.3792,  0.8274],
        [-0.9626,  0.1173, -0.6877, -1.2303]], dtype=torch.float64)


In [37]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[-0.3182,  1.1688,  0.1397,  0.0134],
        [ 1.0353, -1.0697, -0.6564,  0.1725],
        [ 2.5486, -1.1449,  0.5827,  1.0691],
        [-0.0283,  2.1443,  3.3398,  0.8735]])


In [38]:
#In-place addition (change the value of r2)
r2.add_(r)    
print(r2)

tensor([[-0.3182,  1.1688,  0.1397,  0.0134],
        [ 1.0353, -1.0697, -0.6564,  0.1725],
        [ 2.5486, -1.1449,  0.5827,  1.0691],
        [-0.0283,  2.1443,  3.3398,  0.8735]])


In [45]:
print(r2[:,1])


tensor([ 1.1688, -1.0697, -1.1449,  2.1443])


In [40]:
type(r2)

torch.Tensor

In [41]:
print(r2[:,:2])


tensor([[-0.3182,  1.1688],
        [ 1.0353, -1.0697],
        [ 2.5486, -1.1449],
        [-0.0283,  2.1443]])


In [42]:
print(r2[:3,:])

tensor([[-0.3182,  1.1688,  0.1397,  0.0134],
        [ 1.0353, -1.0697, -0.6564,  0.1725],
        [ 2.5486, -1.1449,  0.5827,  1.0691]])


In [43]:
num_ten = r2[2,3]
print(num_ten)


tensor(1.0691)


In [44]:
print(num_ten.item())


1.0691184997558594


In [46]:
print(r2[2,:])

tensor([ 2.5486, -1.1449,  0.5827,  1.0691])


In [47]:
import numpy as np

In [48]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [49]:
#See how the numpy array changed their value.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [50]:
#Converting NumPy Array to Torch Tensor
#See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [51]:

#Move the tensor to the GPU
r2 = r2.cuda()
print(r2)

AssertionError: 
The NVIDIA driver on your system is too old (found version 9010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

In [52]:

#Provide Easy switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

False


In [53]:
#You can also convert a list to a tensor
a = [2,3,4,1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [55]:
data =  [[1., 2.], [3., 4.],
         [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)
print(T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [56]:
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)


tensor([[ 0.1819,  2.0639, -0.0319, -2.0864, -0.2051],
        [-1.1414,  0.7071, -1.0439, -0.2167,  0.4869]])
tensor([[-1.1779, -0.8074, -0.9039,  2.0170,  0.0929],
        [ 1.2739, -0.7787, -0.9556,  2.3959, -0.8406],
        [ 0.1489,  0.3588, -0.5566,  0.4882, -0.2775]])


In [57]:
#Concatenate along the 0 dimension (concatenate rows)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)




tensor([[ 0.1819,  2.0639, -0.0319, -2.0864, -0.2051],
        [-1.1414,  0.7071, -1.0439, -0.2167,  0.4869],
        [-1.1779, -0.8074, -0.9039,  2.0170,  0.0929],
        [ 1.2739, -0.7787, -0.9556,  2.3959, -0.8406],
        [ 0.1489,  0.3588, -0.5566,  0.4882, -0.2775]])


In [58]:
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')



tensor([[-0.4502, -0.1138, -1.2806],
        [-0.9002, -0.1736,  0.1256]])
tensor([[ 0.7395,  0.5307, -0.0941,  2.3104, -2.2007],
        [ 0.7439, -1.4558,  0.1276,  0.2923, -0.6485]])


tensor([[-0.4502, -0.1138, -1.2806,  0.7395,  0.5307, -0.0941,  2.3104, -2.2007],
        [-0.9002, -0.1736,  0.1256,  0.7439, -1.4558,  0.1276,  0.2923, -0.6485]])




In [60]:
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
# Concatenate along the 1 dimension (concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print(con_2)



tensor([[ 1.4126,  1.9407, -0.4544],
        [ 1.2406, -0.9070,  0.8990]])
tensor([[ 0.3793, -0.1954,  0.3182,  0.4464, -1.7052],
        [ 1.1503, -0.1773, -1.9306,  0.5166, -0.3356]])
tensor([[ 1.4126,  1.9407, -0.4544,  0.3793, -0.1954,  0.3182,  0.4464, -1.7052],
        [ 1.2406, -0.9070,  0.8990,  1.1503, -0.1773, -1.9306,  0.5166, -0.3356]])


In [62]:
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_1)
print(tensor_a)


tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])


In [64]:
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)

torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


In [65]:

print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)




tensor([[[0.4466, 0.5923, 0.0836, 0.0969],
         [0.1970, 0.8371, 0.3137, 0.0739],
         [0.1117, 0.0370, 0.0275, 0.9895]],

        [[0.0790, 0.0343, 0.9582, 0.1248],
         [0.4922, 0.6822, 0.7359, 0.8100],
         [0.2990, 0.9130, 0.0331, 0.9066]]])


tensor([[0.0836, 0.3137, 0.0275],
        [0.9582, 0.7359, 0.0331]])


In [66]:
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)

torch.Size([2, 3])


tensor([[[0.0836],
         [0.3137],
         [0.0275]],

        [[0.9582],
         [0.7359],
         [0.0331]]])


In [68]:
tensor_d.shape

torch.Size([2, 3, 1])

In [69]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [70]:
#Now if we backpropagate on s, we can find the gradients of s with respect to x
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [71]:

# By default, Tensors have `requires_grad=False`
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)
#Another way to set the requires_grad = True is
x.requires_grad_()
y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)


False False
None
True


In [72]:
# Now z has the computation history that relates itself to x and y

new_z = z.detach()
print(new_z.grad_fn)
# z.detach() returns a tensor that shares the same storage as ``z``, but with the computation history forgotten. 
#It doesn't know anything about how it was computed.In other words, we have broken the Tensor away from its past history

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

None
True
True
False


In [73]:
#Let's walk in through one last example
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [74]:

m1 = torch.ones(5,5)
m2 = torch.zeros(5,5)
#Perform element-wise multiplaction 
mul = torch.mul(m1,m2)
#Another way to perform element-wise multiplaction 
mul_another = m1*m2
print(mul)
print(mul_another)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
